### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by BaranekD**

### CODE REVIEW

**Comment by BaranekD** [comment]
Problem with single quotes solved, I think PR could be merged.

**Comment by pajavyskocil** [comment]
Please rebase and remove all check === null / !== null in ifs where you check if var is empty.

Function empty returns FALSE for null

**Comment by BaranekD** [comment]
Requested changes done.

**Comment by BaranekD** [comment]
I'm separating this PR into several smaller PRs; because of this I removed all except of the first commit

**Pull request merged**
